/**
 * Golden tests for the MIDITokenizerV2 TypeScript port. The fixtures were
 * generated by the Python reference implementation (SkyTNT midi-model,
 * tools/quantize/make_golden.py) — the TS tokenizer must reproduce them
 * byte-for-byte. Tokenizer drift is the most likely silent-failure mode of
 * the neural tier, so any mismatch here is a hard stop.
 */
import { describe, expect, it } from 'vitest'
import golden from './fixtures/neural-golden.json'
import reference from './fixtures/neural-reference-seed42.json'
import { MidiTokenizerV2, pyRound, type MidiScore } from '../src/generation/neural/tokenizer'
import {
  buildPromptRows,
  eventsToMotif,
  modeToSf,
  motifToEvents,
  sfToKeyMode,
} from '../src/generation/neural/adapters'
import { scalePitchClasses } from '../src/core/theory'
import { makeMotif, makeNote } from './fixtures'

const tok = new MidiTokenizerV2()

describe('vocab layout', () => {
  it('matches the Python reference exactly', () => {
    expect(tok.vocabSize).toBe(golden.tokenizer.vocab_size)
    expect(tok.maxTokenSeq).toBe(golden.tokenizer.max_token_seq)
    expect(tok.padId).toBe(golden.tokenizer.pad_id)
    expect(tok.bosId).toBe(golden.tokenizer.bos_id)
    expect(tok.eosId).toBe(golden.tokenizer.eos_id)
    expect(tok.events).toEqual(golden.tokenizer.events)
    expect(tok.eventParameters).toEqual(golden.tokenizer.event_parameters)
    for (const [p, start] of Object.entries(golden.parameter_id_starts)) {
      expect(tok.parameterIds[p][0]).toBe(start)
    }
  })

  it('pyRound rounds half to even like Python', () => {
    expect(pyRound(0.5)).toBe(0)
    expect(pyRound(1.5)).toBe(2)
    expect(pyRound(2.5)).toBe(2)
    expect(pyRound(2.4)).toBe(2)
    expect(pyRound(2.6)).toBe(3)
  })
})

describe('golden encode/decode', () => {
  it('tokenize() reproduces the reference token rows byte-for-byte', () => {
    const rows = tok.tokenize(golden.encode.inputScore as MidiScore)
    expect(rows).toEqual(golden.encode.tokens)
  })

  it('tokens2event matches the reference event decoding', () => {
    const events = golden.encode.tokens
      .filter((row) => row[0] in tok.idEvents)
      .map((row) => tok.tokens2event(row))
    expect(events).toEqual(golden.decode.events)
  })

  it('detokenize() reproduces the reference output score exactly', () => {
    const score = tok.detokenize(golden.encode.tokens)
    expect(score).toEqual(golden.decode.outputScore)
  })
})

describe('prompt building', () => {
  it('reproduces the seeded reference prompt rows', () => {
    const rows = buildPromptRows(
      { bpm: 120, timeSig: '4/4', key: 'C', mode: 'ionian', patches: new Map([[0, 0]]) },
      tok,
    )
    expect(rows).toEqual(reference.prompt)
  })

  it('maps modes to the key signature with the same pitch set', () => {
    expect(modeToSf('C', 'ionian')).toBe(0)
    expect(modeToSf('D', 'dorian')).toBe(0)
    expect(modeToSf('A', 'aeolian')).toBe(0)
    expect(modeToSf('F', 'lydian')).toBe(0) // F lydian = C major pitch set
    expect(modeToSf('F', 'ionian')).toBe(-1)
    expect(modeToSf('G', 'mixolydian')).toBe(0)
    expect(modeToSf('Eb', 'ionian')).toBe(-3)
  })
})

describe('motif adapters', () => {
  it('round-trips a polyphonic motif through tokens (notes byte-exact)', () => {
    const motif = makeMotif({
      key: 'D',
      mode: 'dorian',
      bars: 2,
      tempo: 120,
      parts: [
        { name: 'lead', instrument: 'piano' },
        { name: 'kit', instrument: 'drums' },
      ],
      notes: [
        makeNote({ pitch: 62, startBeat: 0, durationBeats: 1, velocity: 96, part: 0 }),
        makeNote({ pitch: 65, startBeat: 1, durationBeats: 0.5, velocity: 88, part: 0 }),
        makeNote({ pitch: 69, startBeat: 1.5, durationBeats: 2.5, velocity: 100, part: 0 }),
        makeNote({ pitch: 74, startBeat: 4, durationBeats: 4, velocity: 90, part: 0 }),
        makeNote({ pitch: 36, startBeat: 0, durationBeats: 0.25, velocity: 110, part: 1 }),
        makeNote({ pitch: 38, startBeat: 1, durationBeats: 0.25, velocity: 95, part: 1 }),
        makeNote({ pitch: 42, startBeat: 0.5, durationBeats: 0.125, velocity: 70, part: 1 }),
      ],
    })
    const rows = motifToEvents(motif, tok)
    expect(rows[0][0]).toBe(tok.bosId)
    expect(rows[rows.length - 1][0]).toBe(tok.eosId)

    const raw = eventsToMotif(rows, tok)
    expect(raw.tempo).toBe(120)
    expect(raw.timeSig).toBe('4/4')
    expect(raw.bars).toBe(2)
    // Key signatures can't distinguish relative modes; the pitch SET must match.
    expect(new Set(scalePitchClasses(raw.key, raw.mode))).toEqual(
      new Set(scalePitchClasses('D', 'dorian')),
    )
    // Notes survive byte-exact (16th-grid timing, pitch, velocity).
    const strip = (ns: { pitch: number; startBeat: number; durationBeats: number; velocity: number }[]) =>
      ns
        .map((n) => [n.pitch, n.startBeat, n.durationBeats, n.velocity])
        .sort((a, b) => a[1] - b[1] || a[0] - b[0])
    expect(strip(raw.notes)).toEqual(strip(motif.notes))
    // Drums land on a drums part, melodic notes on a pitched part.
    const drumPart = raw.parts.findIndex((p) => p.instrument === 'drums')
    expect(drumPart).toBeGreaterThanOrEqual(0)
    for (const n of raw.notes) {
      expect((n.part ?? 0) === drumPart).toBe(n.pitch < 48)
    }
  })

  it('decodes the reference generation into a validatable raw motif', () => {
    const raw = eventsToMotif(reference.tokens, tok)
    expect(raw.notes.length).toBeGreaterThan(10)
    expect(raw.tempo).toBe(120)
    expect(raw.timeSig).toBe('4/4')
    for (const n of raw.notes) {
      expect(n.pitch).toBeGreaterThanOrEqual(0)
      expect(n.pitch).toBeLessThanOrEqual(127)
      expect(n.durationBeats).toBeGreaterThan(0)
    }
  })

  it('sfToKeyMode inverts modeToSf pitch-set-wise', () => {
    for (const sf of [-3, -1, 0, 2, 4]) {
      const { key, mode } = sfToKeyMode(sf, 0)
      expect(modeToSf(key, mode)).toBe(sf)
    }
  })
})
