import type { Motif } from '../types'

/** Three contrasting dev fixtures: stepwise, arpeggiated, syncopated. */
export const SAMPLE_MOTIFS: Motif[] = [
  {
    id: 'seed-stepwise',
    name: 'Ember (stepwise)',
    key: 'D',
    mode: 'dorian',
    bars: 2,
    timeSig: '4/4',
    tempo: 96,
    notes: [
      { pitch: 62, startBeat: 0, durationBeats: 1, velocity: 92 },
      { pitch: 64, startBeat: 1, durationBeats: 0.5, velocity: 84 },
      { pitch: 65, startBeat: 1.5, durationBeats: 0.5, velocity: 84 },
      { pitch: 67, startBeat: 2, durationBeats: 1.5, velocity: 100 },
      { pitch: 65, startBeat: 3.5, durationBeats: 0.5, velocity: 78 },
      { pitch: 64, startBeat: 4, durationBeats: 1, velocity: 86 },
      { pitch: 62, startBeat: 5, durationBeats: 2, velocity: 94 },
      { pitch: 60, startBeat: 7, durationBeats: 1, velocity: 72 },
    ],
    parts: [],
    conceptId: null,
    rating: 0,
    discarded: false,
    scaleWarning: false,
    rationale: 'Rising step figure that falls back to rest on the root.',
    createdAt: 0,
    source: { kind: 'seed' },
  },
  {
    id: 'seed-arpeggiated',
    name: 'Orbit (arpeggiated)',
    key: 'A',
    mode: 'aeolian',
    bars: 2,
    timeSig: '4/4',
    tempo: 120,
    notes: [
      { pitch: 57, startBeat: 0, durationBeats: 0.5, velocity: 96 },
      { pitch: 60, startBeat: 0.5, durationBeats: 0.5, velocity: 82 },
      { pitch: 64, startBeat: 1, durationBeats: 0.5, velocity: 88 },
      { pitch: 69, startBeat: 1.5, durationBeats: 1, velocity: 104 },
      { pitch: 67, startBeat: 2.5, durationBeats: 0.5, velocity: 80 },
      { pitch: 64, startBeat: 3, durationBeats: 1, velocity: 86 },
      { pitch: 60, startBeat: 4, durationBeats: 0.5, velocity: 90 },
      { pitch: 64, startBeat: 4.5, durationBeats: 0.5, velocity: 82 },
      { pitch: 67, startBeat: 5, durationBeats: 0.5, velocity: 88 },
      { pitch: 72, startBeat: 5.5, durationBeats: 2.5, velocity: 108 },
    ],
    parts: [],
    conceptId: null,
    rating: 0,
    discarded: false,
    scaleWarning: false,
    rationale: 'Widening arpeggio that lands high and holds.',
    createdAt: 0,
    source: { kind: 'seed' },
  },
  {
    id: 'seed-syncopated',
    name: 'Undertow (syncopated)',
    key: 'F',
    mode: 'mixolydian',
    bars: 2,
    timeSig: '4/4',
    tempo: 108,
    notes: [
      { pitch: 65, startBeat: 0, durationBeats: 0.75, velocity: 100 },
      { pitch: 63, startBeat: 0.75, durationBeats: 0.75, velocity: 84 },
      { pitch: 65, startBeat: 1.5, durationBeats: 1, velocity: 92 },
      { pitch: 70, startBeat: 2.5, durationBeats: 0.5, velocity: 96 },
      { pitch: 69, startBeat: 3.5, durationBeats: 1, velocity: 88 },
      { pitch: 65, startBeat: 4.5, durationBeats: 0.75, velocity: 94 },
      { pitch: 67, startBeat: 5.25, durationBeats: 0.75, velocity: 86 },
      { pitch: 60, startBeat: 6, durationBeats: 2, velocity: 90 },
    ],
    parts: [],
    conceptId: null,
    rating: 0,
    discarded: false,
    scaleWarning: false,
    rationale: 'Off-beat pushes with a flat-seventh color tone.',
    createdAt: 0,
    source: { kind: 'seed' },
  },
]
